baseurl: /
permalink: /:title/
paginate: 8
paginate_path: "/blog/:num/"
markdown: kramdown
relative_permalinks: false
gems: [jekyll-paginate]
excerpt_separator: <!--more-->
exclude: ["README.md","Gemfile","Gemfile.lock","CNAME","gruntfile.js","package.json","node_modules","js/layout","js/components/ouibounce.js","js/production.js",vendor,"Rakefile","Procfile","config.ru"]

sass:
  sass_dir: _sass
  style: :compressed
